[workspace]
resolver = "2"

members = [
    "state", "merkle", "state_commitment", "execution", "example", "state_management", "api", "trollup-solana-programs/on-chain-program-example", "validator", "zk"]

